### ISSUE TITLE
Action upon logging in

### ISSUE THREAD

**Issue by ksharo** [AlexRubino/Placecard#63]
When a customer logs in:
1. If they have not yet created an event (or all events have passed), bring them to the "Create an event" page.
2. If they have only created one event (or there is only one in the future), bring them to that event's dashboard.
3. If they have many events, bring them to the user dashboard (the page where it says "Welcome back!")

**Comment by kaiqichee** [comment]
pushed a change, updated loggedin state upon google login and added that to use state trigger in OAuthoDialogList.tsx
